Hw10 program optimization
dingowd/otus pull request #14
Opened 2021-12-24 12:07 UTC by dingowd

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-12-24 12:30 UTC, dingowd commented
wait a moment. Напишу бенчмарк

2021-12-26 10:59 UTC, dingowd commented
на моей машине тесты проходят. кроме того, на гитхабе тоже проходили, но сегодня что-то не проходит тест на скорость работы

2021-12-26 13:30 UTC, agneum requested changes
Спасибо за вариант решения. 
Есть предложение по оптимизации, чтобы пройти тесты

2021-12-26 13:30 UTC, agneum commented on hw10_program_optimization/stats.go
>  }
В рамках решения задачи можно не хранить данные о пользователях и сразу подсчитывать домены. Думаю, это должно немного оптимизировать программу

2021-12-26 20:50 UTC, dingowd commented on hw10_program_optimization/stats.go
>  }
думал о таком варианте. но все-таки решил сделать так. к сожалению очень мало времени, я и так отстаю. если появится возможность, то обязательно переделаю.

2021-12-27 13:56 UTC, agneum approved these changes
Спасибо за правки. Отличная работа
10/10

2022-03-06 21:31 UTC, merged